[unstable]
#namespaced-features = true
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "./fruitrunner"
runner = "probe-run --chip nrf52840_xxAA"

[build]
target = "thumbv7em-none-eabihf"
# required due to: https://github.com/rust-lang/rust/issues/96486
rustflags = ["-Zshare-generics=n"]
